name: Unix

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      # Increase this value to reset cache
      env: {CACHE_NUMBER: 0}
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ matrix.python-version }}

    - uses: conda-incubator/setup-miniconda@v2
      name: Setup conda
      with:
        auto-update-conda: true
        activate-environment: testing
        auto-activate-base: false
        channels: conda-forge,defaults
        channel-priority: true

    - shell: bash -l {0}
      name: Install dependencies
      run: |
        conda install -c conda-forge python=${{ matrix.python-version }} numpy mpi4py;
        pip3 install flake8;
        pip3 install -r requirements.txt;
        python setup.py install
    - shell: bash -l {0}
      name: Lint with flake8
      run: |
        flake8 ./libe_opt
    - shell: bash -l {0}
      name: Run unit tests
      run: |
        python -m pytest tests/
